### ISSUE TITLE
Possible to fetch images without using Kirby user accounts

### ISSUE THREAD

**Issue by olach** [bnomei/kirby-instagram-api#1]
I started implementing this plugin, but hit this roadblock when I realized that the Instagram connection info must be tied to a Kirby user account. Is it possible to use this plugin without specify a Kirby user account?

Wouldn't it be possible to save all the necessary connection info (user id, secret, token etc) in the config file, instead in a users settings?

In my case I don't want different users to be able to fetch users from their Instagram account. I just want to display my clients Instagram images on their site. Maybe it is on the roadmap?

**Comment by bnomei** [comment]
do you need a way to get the token without a user as well? or do your have these already?

**Comment by olach** [comment]
The token is not a problem. There are several sites that allow you to get the token. You can also get it via the terminal. But yes, it would be nice if the plugin would simplify this process.

**Comment by bnomei** [comment]
should now be possible with v.0.7.0-beta. but I had not time to test it thoroughly. 
please do report back so I can close this issue.

https://github.com/bnomei/kirby-instagram-api#use-without-extending-a-kirby-user-v07

**Comment by olach** [comment]
I just tried it, and yes, I can fetch images from Instagram without involving Kirby users.

I set the following settings in my config.php:
```php
c::set('plugin.instagram-api.client-id', 'MY_CLIENT_ID');
c::set('plugin.instagram-api.client-secret', 'MY_CLIENT_SECRET');
```

Then I used this code to fetch the data from Instagram:
```php
$logindata = [
    'account'   => 'MY_ACCOUNT',
    'userid'    => 'MY_USERID',
    'token'     => 'MY_TOKEN',
];
$result = $page->instagramapi($logindata, 'users/self/media/recent');
```

However, I did notice that the `account` and `userid` settings is not used. If I set these two settings to random values, I could still fetch my data from Instagram. But if the settings are empty strings or missing, the plugin generates an error: `Missing Account values.`

Maybe you can adjust your code so that just the token is necessary in the `$logindata` array? This of course if the endpoint doesn't need the account and userid settings.

Even better would be to be able to set the **default** token in the config file:
```php
c::set('plugin.instagram-api.client-id', 'MY_CLIENT_ID');
c::set('plugin.instagram-api.client-secret', 'MY_CLIENT_SECRET');
c::set('plugin.instagram-api.client-token', 'MY_CLIENT_TOKEN');
```

And then just use the following code to fetch the data from Instagram:
```php
$result = $page->instagramapi('users/self/media/recent');
```

And if another endpoint needs additional data, the second parameter could be used for that:
```php
$result = $page->instagramapi('users/self/media/recent', $logindata);
```

**Comment by bnomei** [comment]
you can set the default value overriding everything else now with v0.7.2-beta.
to allow ommiting the `instagramapi`-function param would be complex, but you can now 

- use the `TOKEN` or 
- set default and use `null`

**Comment by olach** [comment]
I tried v0.7.2-beta and now I can't get it to work anymore. I only get this error message: `Missing Account values.`

I tried several different ways with no luck:

```php
$result = $page->instagramapi(null, 'users/self/media/recent');
$result = $page->instagramapi(c::get('plugin.instagram-api.client-token'), 'users/self/media/recent');
$result = $page->instagramapi('MY_TOKEN', 'users/self/media/recent');
```

Just a reminder, I don't know how you have coded this, but setting the token in the config should set the default token. You should always be able to override this default token when calling the instagramapi method.

```php
c::set('plugin.instagram-api.client-token', 'MY_TOKEN');
$result = $page->instagramapi('ANOTHER_TOKEN', 'users/self/media/recent');
```

Another thing, since the token is not assigned to the Instagram client, but instead one of the connected users of the client, you should rename the config name to something like:
```php
c::set('plugin.instagram-api.default-token', 'MY_DEFAULT_TOKEN');
```

**Comment by bnomei** [comment]
sorry not my lucky day it seems... will fix it now.

**Comment by bnomei** [comment]
thanks for your patience. please try with v0.7.3. it worked at my test-server at least. 🙄

**Comment by olach** [comment]
Thanks. This worked better. Only one thing that not works as expected. If you have set the token in your config file:
```php
c::set('plugin.instagram-api.default-token', 'MY_DEFAULT_TOKEN');
```

Then you should be able to overwrite this with another token when calling the `instagramapi` method:
```php
$result = $page->instagramapi('ANOTHER_TOKEN', 'users/self/media/recent');
```

I think its common practice that you should always be able to overwrite default configs.

**Comment by bnomei** [comment]
yes good point. done so in v0.7.4.

**Comment by olach** [comment]
Sweet. Thanks. I'm closing this issue now.
