### ISSUE TITLE
other endpoint than users/self/media/recent

### ISSUE THREAD

**Issue by movingwater** [bnomei/kirby-instagram-api#4]
I tried to set another endpoint like: tags/{tagname}/media/recent.

But know I get the message, that I have to re-authorize with scope=public_content. Somehow I didn't get it to work. I tried it, with adding "scope=public_content" to the authorize link.

How can I use other endpoints? Thanks for your help..

And here the complete message:
`Response HTTP Status Code : 400
Response HTTP Body : {"meta": {"code": 400, "error_type": "OAuthPermissionsException", "error_message": "This request requires scope=public_content, but this access token is not authorized with this scope. The user must re-authorize your application with scope=public_content to be granted this permissions."}}
			// show error message this plugin provides
		echo brick('code', $result);`

**Comment by bnomei** [comment]
you are right. the plugin currently only supports authorisation of `basic` permission scope. i will think about a simple solution for changing that. but even if you the auth-link has `scope=public_content` it will not work for *sandbox instagram apps* afaik.

getting public content requires you to create an *instagram app*, [submit it for review](https://www.instagram.com/developer/review/) and **get it approved**. you can read more about [pemission scopes here](https://www.instagram.com/developer/authorization/).

**Comment by bnomei** [comment]
added a new release adding a [permission score setting](https://github.com/bnomei/kirby-instagram-api#plugininstagram-apiscope-v09). please try again with [v0.9.0-beta](https://github.com/bnomei/kirby-instagram-api/releases/tag/v0.9.0-beta). 

```php
c::set('plugin.instagram-api.scope', 'public_content');
```
