### ISSUE TITLE
Allow user to handle cURL errors

### ISSUE THREAD

**Issue by LeBenLeBen** [bnomei/kirby-instagram-api#8]
Today if the curl fails, the plugin does this:

```
die('Error: "' . curl_error($ch) . '" - Code: ' . curl_errno($ch));
```

This is an issue because as soon as something bad happen, the page stops rendering and the user experience gets pretty bad.

It would be great if the plugin could throw an exception instead so it would be possible to catch it to do some graceful degradation when it happens.

**Comment by bnomei** [comment]
good point. will change that asap.

**Comment by bnomei** [comment]
please close this issue if you are satisfied with changes made.

**Comment by LeBenLeBen** [comment]
@bnomei Perfect, thank you!
